version: "3.9"

services:
  backend_mcp:
    build: .
    image: ldims/backend_mcp:latest
    container_name: backend_mcp
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3001:3001" # HOST:CONTAINER
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ldims_network

networks:
  ldims_network:
    external: true
